// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Arbetsprov.Migrations
{
    [DbContext(typeof(PriceCheckContext))]
    [Migration("20231014123852_AddedActiveServiceTime")]
    partial class AddedActiveServiceTime
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("DiscountDaysPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiscountPercentage")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Service")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("DiscountDaysPeriod");
                });

            modelBuilder.Entity("PriceOverride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float?>("ServiceAPrice")
                        .HasColumnType("REAL");

                    b.Property<float?>("ServiceBPrice")
                        .HasColumnType("REAL");

                    b.Property<float?>("ServiceCPrice")
                        .HasColumnType("REAL");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PriceOverride");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DiscountDaysPeriod", b =>
                {
                    b.HasOne("User", null)
                        .WithMany("DiscountDaysPeriods")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("PriceOverride", b =>
                {
                    b.HasOne("User", null)
                        .WithMany("PriceOverrides")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
